/**
 * Wefly Track API
 * API for managing and retrieving track data for Wefly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeflyTrackApi);
  }
}(this, function(expect, WeflyTrackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeflyTrackApi.Metadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Metadata', function() {
    it('should create an instance of Metadata', function() {
      // uncomment below and update the code to test Metadata
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be.a(WeflyTrackApi.Metadata);
    });

    it('should have the property pilotname (base name: "pilotname")', function() {
      // uncomment below and update the code to test the property pilotname
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property maxAltitude (base name: "maxAltitude")', function() {
      // uncomment below and update the code to test the property maxAltitude
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property lastTime (base name: "lastTime")', function() {
      // uncomment below and update the code to test the property lastTime
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property startPosition (base name: "startPosition")', function() {
      // uncomment below and update the code to test the property startPosition
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property lastPosition (base name: "lastPosition")', function() {
      // uncomment below and update the code to test the property lastPosition
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property activity (base name: "activity")', function() {
      // uncomment below and update the code to test the property activity
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property area (base name: "area")', function() {
      // uncomment below and update the code to test the property area
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property maxGain (base name: "maxGain")', function() {
      // uncomment below and update the code to test the property maxGain
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property dataSource (base name: "dataSource")', function() {
      // uncomment below and update the code to test the property dataSource
      //var instance = new WeflyTrackApi.Metadata();
      //expect(instance).to.be();
    });

  });

}));
