/**
 * Wefly Track API
 * API for managing and retrieving track data for Wefly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeflyTrackApi);
  }
}(this, function(expect, WeflyTrackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeflyTrackApi.Path();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Path', function() {
    it('should create an instance of Path', function() {
      // uncomment below and update the code to test Path
      //var instance = new WeflyTrackApi.Path();
      //expect(instance).to.be.a(WeflyTrackApi.Path);
    });

    it('should have the property points (base name: "points")', function() {
      // uncomment below and update the code to test the property points
      //var instance = new WeflyTrackApi.Path();
      //expect(instance).to.be();
    });

    it('should have the property times (base name: "times")', function() {
      // uncomment below and update the code to test the property times
      //var instance = new WeflyTrackApi.Path();
      //expect(instance).to.be();
    });

  });

}));
