/**
 * Wefly Track API
 * API for managing and retrieving track data for Wefly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WeflyTrackApi);
  }
}(this, function(expect, WeflyTrackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WeflyTrackApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('apiTrackTrackIdDelete', function() {
      it('should call apiTrackTrackIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiTrackTrackIdDelete
        //instance.apiTrackTrackIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiTracksMetadataGet', function() {
      it('should call apiTracksMetadataGet successfully', function(done) {
        //uncomment below and update the code to test apiTracksMetadataGet
        //instance.apiTracksMetadataGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiTracksPathsGet', function() {
      it('should call apiTracksPathsGet successfully', function(done) {
        //uncomment below and update the code to test apiTracksPathsGet
        //instance.apiTracksPathsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiTracksPost', function() {
      it('should call apiTracksPost successfully', function(done) {
        //uncomment below and update the code to test apiTracksPost
        //instance.apiTracksPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
