/**
 * Wefly Track API
 * API for managing and retrieving track data for Wefly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Path from './Path';

/**
 * The ApiTracksPathsGet200Response model module.
 * @module model/ApiTracksPathsGet200Response
 * @version 1.0.0
 */
class ApiTracksPathsGet200Response {
    /**
     * Constructs a new <code>ApiTracksPathsGet200Response</code>.
     * @alias module:model/ApiTracksPathsGet200Response
     */
    constructor() { 
        
        ApiTracksPathsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiTracksPathsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiTracksPathsGet200Response} obj Optional instance to populate.
     * @return {module:model/ApiTracksPathsGet200Response} The populated <code>ApiTracksPathsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiTracksPathsGet200Response();

            if (data.hasOwnProperty('trackId')) {
                obj['trackId'] = ApiClient.convertToType(data['trackId'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = Path.constructFromObject(data['path']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiTracksPathsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiTracksPathsGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['trackId'] && !(typeof data['trackId'] === 'string' || data['trackId'] instanceof String)) {
            throw new Error("Expected the field `trackId` to be a primitive type in the JSON string but got " + data['trackId']);
        }
        // validate the optional field `path`
        if (data['path']) { // data not null
          Path.validateJSON(data['path']);
        }

        return true;
    }


}



/**
 * @member {String} trackId
 */
ApiTracksPathsGet200Response.prototype['trackId'] = undefined;

/**
 * @member {module:model/Path} path
 */
ApiTracksPathsGet200Response.prototype['path'] = undefined;






export default ApiTracksPathsGet200Response;

