/**
 * Wefly Track API
 * API for managing and retrieving track data for Wefly.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import Path from './Path';

/**
 * The Track model module.
 * @module model/Track
 * @version 1.0.0
 */
class Track {
    /**
     * Constructs a new <code>Track</code>.
     * @alias module:model/Track
     */
    constructor() { 
        
        Track.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Track</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Track} obj Optional instance to populate.
     * @return {module:model/Track} The populated <code>Track</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Track();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = Path.constructFromObject(data['path']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Track</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Track</code>.
     */
    static validateJSON(data) {
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          Metadata.validateJSON(data['metadata']);
        }
        // validate the optional field `path`
        if (data['path']) { // data not null
          Path.validateJSON(data['path']);
        }

        return true;
    }


}



/**
 * @member {module:model/Metadata} metadata
 */
Track.prototype['metadata'] = undefined;

/**
 * @member {module:model/Path} path
 */
Track.prototype['path'] = undefined;






export default Track;

